image: java:latest

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - javac src/org/sindercube/serpex/*.java -d bin
  artifacts:
    paths:
     - bin

deploy:
  stage: deploy
  script:
    - jar -cef org.sindercube.serpex.Application serpex.jar -C bin .
  artifacts:
    paths:
      - serpex.jar
    expire_in: never
