modLoader = 'lowcodefml'
loaderVersion = '[0,)'
license = 'LGPL-3.0-or-later'
showAsResourcePack = false
mods = [{
	modId = 'server_unpacker',
	version = '0.0.0',
	displayName = 'Server Unpacker',
	description = 'Extract those pesky Server Resource Packs',
	logoFile = 'icon.png',
	authors = 'Sindercube',
	displayURL = 'https://modrinth.com/mod/server-unpacker'
}]
